target 'Notes' do
    pod 'JGProgressHUD'
end

target 'NotesTests' do
    pod 'Kiwi', '3.0.0'
    pod 'Nimble', '7.3.0'
    pod 'Quick', '1.3.0'
end

target 'NotesUIKIFTests' do
    pod 'KIF/IdentifierTests', :configurations => ['Debug']
    pod 'KIF', :configurations => ['Debug']
end