target 'Notes' do
    pod 'JGProgressHUD'
end

target 'NotesTests' do
    pod 'Kiwi', '3.0.0'
    pod 'Nimble', '8.0.1'
    pod 'Quick', '2.1.0'
end

target 'NotesUIKIFTests' do
    pod 'KIF/IdentifierTests', :configurations => ['Debug']
    pod 'KIF', :configurations => ['Debug']
end